### ISSUE TITLE
PaymentView() takes no argument error

### ISSUE THREAD

**Issue by gipsbrian** [odero/django-pesapal#19]
so am very new to Pesapal and i cloned the django nod into my project, 
so in my view i created a class PaymentView that extends the PaymentRequestMixin  
`class PaymentView(PaymentRequestMixin):
    def get_pesapal_payment_iframe(self):
        order_info = {
            'first_name': 'firstname',
            'last_name': 'lastname',
            'amount': 1000,
            'description': 'test payment',
            'reference': 'Test-payment123',  
            'email': 'email@gmail.com',
        }
        iframe_src_url = self.get_payment_url(**order_info)
        return iframe_src_url`
I keep on getting this error 
`Exception Type: | TypeError
PaymentView() takes no arguments
`
Am using Django 2.x and python3.x.

**Comment by anitaakoth** [comment]
Hi @wizGipsBrian 

Where are you initializing this class? 
Paste your urls file here.

**Comment by gipsbrian** [comment]
from .views import ( 
        PaymentView,
)

urlpatterns = [
path('pay/', PaymentView, name='pay'),

]

I implemented the PaymentView in my own view, and imported the  PaymentRequestMixin

from django_pesapal.views import PaymentRequestMixin

class PaymentView(PaymentRequestMixin):

    def get_pesapal_payment_iframe(self, request, *args, **kwargs):

        '''
        Authenticates with pesapal to get the payment iframe src
        '''
        order_info = {
            'first_name': 'firstname',
            'last_name': 'lastname',
            'amount': 1000,
            'description': 'test payment',
            'reference': 'Test-256',  # some object id
            'email': 'email@gmail.com',
        }

        iframe_src_url = self.get_payment_url(**order_info)
        return iframe_src_url

**Comment by odero** [comment]
Your url patterns are the problem. You should be using `PaymentView.as_view()` This: 
```
urlpatterns = [
   path('pay/', PaymentView.as_view(), name='pay'),
]
```
