### ISSUE TITLE
Working example of fetching payment status by using merchant_id and transaction_id

### ISSUE THREAD

**Issue by sakalig** [odero/django-pesapal#20]
Hi.
This isn't a standard issue, just a request for guidance. Since stackoverflow hasn't fully helped me, I might as well share my problem here.
So far, I have managed to fetch the merchant_id and transaction_id after a successful payment. From there, I haven't been able to fetch payment status with said details. This api's docs only show the payment options view, and not the fetch status (btw multiple examples available in php, not django).
Help/examples are appreciated. Thanks

**Comment by odero** [comment]
@gebsakali Run the example in the sandbox directory. It provides an example of what you are asking for.

**Comment by sakalig** [comment]
@odero I went through your example, but it only shows how to retrieve the iframe. I'm talking about after redirecting to the transaction_complete page (custom page). Something like this:

if request.method == 'GET':
            postdata = request.GET.copy()
            if postdata['pesapal_transaction_tracking_id'] and postdata['pesapal_merchant_reference']:

Everytime I try to use the above details to fetch the status, it shows an invalid signature error.

Thanks

**Comment by odero** [comment]
See attached. You see the "check status" button, it does what you're asking for. If you run the example project inside the sandbox, you'll see it at work.

![screen shot 2018-10-02 at 16 49 07](https://user-images.githubusercontent.com/380686/46352831-672f1180-c663-11e8-9f42-54f5721aa617.png)

**Comment by sakalig** [comment]
I reached this dialog and hit the check status button. I've been trying to fetch the status (SUCCESS, PENDING) in django code so as to update the DB but haven't been able to. Is there a way within the views to fetch the status ... should I override a function or is that unnecessary?

**Comment by odero** [comment]
As I stated before, that "check status" button does exactly what you are asking for. You can see how it's been implemented by following the flow from this line.

https://github.com/odero/django-pesapal/blob/47b5172d8eadf08e49c1c7b9b0d20b7de6c1269a/django_pesapal/views.py#L280

the app maintains its own model called `Transaction`. This is updated automatically with the current status of the transaction when you click on "check status" or when you receive the IPN from pesapal.

**In short:** You check the status by checking the `transaction.payment_status` field in Transaction Model, _NOT_ by calling pesapal. If `payment_status` still pending you can redirect the user to some page where they continue waiting or do something else.

If you check the docs https://django-pesapal.readthedocs.io/en/latest/readme.html#configuration you can modify and set your own model by overriding `PESAPAL_TRANSACTION_MODEL`. Don't see the benefit in doing that but you can do it if you wish.

**Comment by sakalig** [comment]
Thanks for the steady feedback @odero . I got it to work by overriding the views in view.py and relevant urls. I also added the Transaction model.
