### ISSUE TITLE
'PaymentView' has no attribute 'as_view'

### ISSUE THREAD

**Issue by iamfeysal** [odero/django-pesapal#23]
am trying to use Django-pesapal for my project but I am getting this error whenever I load my project `'PaymentView' has no attribute 'as_view'` when I try to remove the as_view() in my app URL ` path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),`, i get this error **Paymentview takes no argument**

Thank in Advance

**Comment by odero** [comment]
Show your definition of `PaymentView` and `urls.py`

**Comment by Denyo-255** [comment]
I'm having the same issue when i put as_view() function to a Payment.

**Comment by odero** [comment]
If issues is still occurring, you can reopen

**Comment by kmanyara** [comment]
Please reopen this. I'm having the same issue:

`
  class PaymentView(PaymentRequestMixin):
      def get_pesapal_payment_iframe(self):
          order_info = {
              'first_name': 'Some',
              'last_name': 'User',
              'amount': 100,
              'description': 'Payment for X',
              'reference': 2,  # some object id
              'email': 'user@example.com',
          }
          iframe_src_url = self.get_payment_url(**order_info)
          return iframe_src_url
`

Error: 

`'PaymentView' has no attribute 'as_view'`

**Comment by odero** [comment]
Have a look at the sandbox project.
Here's how to do it

https://github.com/odero/django-pesapal/blob/2902ab559dbcfc70dccbdd48916a668b0374351c/sandbox/testapp/views.py#L7

**Comment by kmanyara** [comment]
> Have a look at the sandbox project. Here's how to do it
> 
> https://github.com/odero/django-pesapal/blob/2902ab559dbcfc70dccbdd48916a668b0374351c/sandbox/testapp/views.py#L7

Thanks for the quick reply. All good now.
